title: jk-minima-gpt
description: Jekyll blog with the Minima theme
theme: minima
baseurl: "/jk-minima-gpt"
url: "https://devAItester.github.io"
markdown: kramdown
permalink: pretty

exclude:
  - posts
  - scripts
